app/bodega/urls.py
from django.conf.urls import url
from django.contrib import admin
from app.bodega.views import *

urlpatterns = [

    # URLS GESTION DE PERSONAS
    url(r'^ListarPersonas/$', ListarPersonas.as_view(), name='lis-per'),
    url(r'^CrearPersona/$', CrearPersona.as_view(), name='cre-per'),
    url(r'^ActualizarPersona/(?P<pk>[0-9]+)/$',
        ActualizarPersona.as_view(), name='act-per'),
    url(r'^EliminarPersona/(?P<pk>[0-9]+)/$',
        EliminarPersona.as_view(), name='elm-per'),

    # URLS GESTION DE RECURSOS
    url(r'^ListarRecursos/$', ListarRecursos.as_view(), name='lis-rec'),
    url(r'^CrearRecurso/$', CrearRecurso.as_view(), name='cre-rec'),
    url(r'^ActualizarRecurso/(?P<pk>[0-9]+)/$',
        ActualizarRecurso.as_view(), name='act-rec'),
    url(r'^EliminarRecurso/(?P<pk>[0-9]+)/$',
        EliminarRecurso.as_view(), name='elm-rec'),

    # URLS GESTION DE ASIGNACIONES
    url(r'^ListarAsignaciones/$', ListarAsignaciones.as_view(), name='lis-asi'),
    url(r'^ListarPersonaRecursos/$',
        ListarPersonaRecursos.as_view(), name='lis-per-rec'),
    url(r'^CrearAsignacion/$', CrearAsignacion.as_view(), name='cre-asi'),
    url(r'^DetalleAsignacion/(?P<pk>[0-9]+)/$',
        DetalleAsignacion.as_view(), name='det-asi'),

    url(r'^TrasladarRecursos/(?P<pk>[0-9]+)/$',
        TrasladarRecursos.as_view(), name='tra-rec'),

]

pruebadeltec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from pruebadeltec.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),

    url(r'^',
        include('app.bodega.urls', namespace='bodega')),
]

templates/includes/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Prueba - Deltec</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">


    <!-- Bootstrap Core CSS -->
    <!--<link rel='stylesheet' href="{% static 'css/bootstrap.css' %}">-->
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- MetisMenu CSS -->
    <link rel='stylesheet' href="{% static 'css/metisMenu.css' %}">

    <!-- Custom CSS -->
    <link rel='stylesheet' href="{% static 'css/sb-admin-2.css' %}">

    <!-- Custom Fonts -->
    <link rel='stylesheet' href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <!-- Nuestro Estilo -->
    <link rel='stylesheet' href="{% static 'css/mi_estilo.css' %}"> {% block files_head %}{% endblock %}
</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar nav-mi navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; background-color: #3d3d3d">
            <!-- Panel de Navegacion Lateral-->
            <div class="navbar-header nav-mi">
                  <b><a class="navbar-brand" href="{%url 'index'%}" style= "color:white;">DELTEC</a></b>
            </div>
            {% include "includes/panel-nav.html" %}
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">


                {% block content %}{% endblock %}

            </div>
        </div>

    </div>
    <!-- /#wrapper -->
    {% block files_food %}
    <!-- jQuery -->
    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js'%}"></script>

    {% endblock %}


    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script type="text/javascript" src="{% static 'js/metisMenu.js'%}"></script>

    <!-- Custom Theme JavaScript -->
    <script type="text/javascript" src="{% static 'dist/js/sb-admin-2.js'%}"></script>
</body>

</html>

templates/includes/panel-nav.html
<div class="navbar-default sidebar" role="navigation" style="background-color:#3d3d3d;">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav nav-mi" id="side-menu">
            <li class="li-men-u">
                <a class="a-men" href="#" class="a-men"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Personal<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level nav-mi">
                    <li>
                      <a class="a-men" href="{% url 'bodega:lis-per' %}"><i class="fa fa-address-book" aria-hidden="true"></i> Listar Personas</a>
                    </li>
                    <li>
                      <a class="a-men" href="{% url 'bodega:cre-per' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Agregar Persona</a>
                    </li>
                </ul>
            </li>
            <li class="li-men-u">
                <a class="a-men" href="#" class="a-men"><i class="fa fa-cubes" aria-hidden="true"></i> Recursos<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level nav-mi">
                    <li>
                      <a class="a-men" href="{% url 'bodega:lis-rec' %}"><i class="fa fa-list-ol" aria-hidden="true"></i> Listar Recursos</a>
                    </li>
                    <li>
                      <a class="a-men" href="{% url 'bodega:cre-rec' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i></i> Agregar Recurso</a>
                    </li>
                </ul>
            </li>
            <li class="li-men-u">
                <a class="a-men" href="#" class="a-men"><i class="fa fa-check-square-o" aria-hidden="true"></i> Asignarciones<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level nav-mi">
                    <li>
                      <a class="a-men" href="{% url 'bodega:lis-asi' %}"><i class="fa fa-hourglass-end" aria-hidden="true"></i> Historial de Asignaciones</a>
                    </li>
                    <li>
                      <a class="a-men" href="{% url 'bodega:lis-per-rec' %}"><i class="fa fa-list-ol" aria-hidden="true"></i> Personas con Recursos</a>
                    </li>
                    <li>
                      <a class="a-men" href="{% url 'bodega:cre-asi' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i>  Asignar Recurso a Persona</a>
                    </li>

                </ul>
            </li>

        </ul>
    </div>
</div>