app/bodega/urls.py
from django.conf.urls import url
from django.contrib import admin
from app.bodega.views import *

urlpatterns = [

    # URLS GESTION DE PERSONAS
    url(r'^ListarPersonas/$', ListarPersonas.as_view(), name='lis-per'),
    url(r'^CrearPersona/$', CrearPersona.as_view(), name='cre-per'),
    url(r'^ActualizarPersona/(?P<pk>[0-9]+)/$',
        ActualizarPersona.as_view(), name='act-per'),
    url(r'^EliminarPersona/(?P<pk>[0-9]+)/$',
        EliminarPersona.as_view(), name='elm-per'),

    # URLS GESTION DE RECURSOS
    url(r'^ListarRecursos/$', ListarRecursos.as_view(), name='lis-rec'),
    url(r'^CrearRecurso/$', CrearRecurso.as_view(), name='cre-rec'),
    url(r'^ActualizarRecurso/(?P<pk>[0-9]+)/$',
        ActualizarRecurso.as_view(), name='act-rec'),
    url(r'^EliminarRecurso/(?P<pk>[0-9]+)/$',
        EliminarRecurso.as_view(), name='elm-rec'),

    # URLS GESTION DE ASIGNACIONES
    url(r'^ListarAsignaciones/$', ListarAsignaciones.as_view(), name='lis-asi'),
    url(r'^ListarPersonaRecursos/$',
        ListarPersonaRecursos.as_view(), name='lis-per-rec'),
    url(r'^CrearAsignacion/$', CrearAsignacion.as_view(), name='cre-asi'),
    url(r'^DetalleAsignacion/(?P<pk>[0-9]+)/$',
        DetalleAsignacion.as_view(), name='det-asi'),

    url(r'^TrasladarRecursos/(?P<pk>[0-9]+)/$',
        TrasladarRecursos.as_view(), name='tra-rec'),

]

pruebadeltec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from pruebadeltec.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),

    url(r'^',
        include('app.bodega.urls', namespace='bodega')),
]

templates/recurso/CrearPersona.html
{% extends "includes/base.html" %}
{% load crispy_forms_tags %}
{% load static %} {% block files_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{% endblock %} {% block content %}
<br>
<div class="panel col-sm-offset-2 col-sm-8 w3-card-4 w3-border-green">
    <br>
    <form method="post">
        <center>
            <h3><b>Nueva Persona del Sistema</b></h3></center>
        <hr>
        {% csrf_token %} {% crispy form %}
    </form>
</div>

{%endblock%}

templates/recurso/CrearRecurso.html
{% extends "includes/base.html" %}
{% load crispy_forms_tags %}
{% load static %} {% block files_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{% endblock %} {% block content %}
<br>
<div class="panel col-sm-offset-2 col-sm-8 w3-card-4 w3-border-green">
    <br>
    <form method="post">
        <center>
            <h3><b>Nuevo Recurso</b></h3></center>
        <hr>
        {% csrf_token %} {% crispy form %}
    </form>
</div>

{%endblock%}

templates/recurso/EliminarRecurso.html
{% extends "includes/base.html" %}
{% block content %}
<center>
    <h1><b>Eliminaras un Recurso de la Bodega</b></h1>
    <hr>
</center>
{% if msj %}
<div class="alert alert-danger">
<strong>Error!</strong> {{msj}}   <a class="btn btn-success" href="{% url 'bodega:lis-rec' %}"> Atras</a>
</div>
{% else %}
<div class="col-sm-offset-2 col-sm-7 panel panel-default" >
    <form method="post">
      <h2>¿Desea Eliminar el Recurso {{object.nombre}} ?</h2>
        {% csrf_token %}
        <hr>
        <center>
          <input type="submit" class="btn btn-danger"name="Eliminar" value="Eliminar">
          <a class="btn btn-success" href="{% url 'bodega:lis-rec' %}"> Cancelar</a>
        </center>
    </form>
    <br>
</div>
{% endif %}
{% endblock %}

templates/recurso/ListarRecursos.html
{% extends "includes/base.html" %} {% block content %}
<center>
  <h1>Listado de Recursos en el Sistema</h1>

</center>
<hr>
<div class="container-fluid ">
    <div class="table-responsive">
        <table class="table w3-table-all w3-card-4">

            <thead class="thead-inverse">
                <tr>
                    <th>Codigo</th>
                    <th>Serie</th>
                    <th>Nombre</th>
                    <th>Estado</th>
                    <th>Marca</th>
                    <th>Modificar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for recurso in lista %}
                <tr>
                    <td>
                        {{ recurso.codigo}}
                    </td>
                    <td>
                        {{ recurso.serie}}
                    </td>
                    <td>
                        {{ recurso.nombre}}
                    </td>
                    <td>
                        {{ recurso.estado}}
                    </td>
                    <td>
                        {{ recurso.marca}}
                    </td>
                    <td>
                      <a class="btn btn-success" href="{% url 'bodega:act-rec' recurso.id %}" name="btn-mod">MODIFICAR</a>
                    </td>
                    <td>
                      <a class="btn btn-danger"  href="{% url 'bodega:elm-rec' recurso.id %}" name="btn-elm">ELIMINAR</a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock%}

templates/recurso/ModificarRecurso.html
{% extends "includes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<br>
<div class="panel col-sm-offset-2 col-sm-8 w3-card-4 w3-border-green">

    <form method="post">
      <center><h3><b>Modificar Recurso</b></h3></center><hr>

        {% csrf_token %} {% crispy form %}

    </form>

</div>
{%endblock%}