app/bodega/urls.py
from django.conf.urls import url
from django.contrib import admin
from app.bodega.views import *

urlpatterns = [

    # URLS GESTION DE PERSONAS
    url(r'^ListarPersonas/$', ListarPersonas.as_view(), name='lis-per'),
    url(r'^CrearPersona/$', CrearPersona.as_view(), name='cre-per'),
    url(r'^ActualizarPersona/(?P<pk>[0-9]+)/$',
        ActualizarPersona.as_view(), name='act-per'),
    url(r'^EliminarPersona/(?P<pk>[0-9]+)/$',
        EliminarPersona.as_view(), name='elm-per'),

    # URLS GESTION DE RECURSOS
    url(r'^ListarRecursos/$', ListarRecursos.as_view(), name='lis-rec'),
    url(r'^CrearRecurso/$', CrearRecurso.as_view(), name='cre-rec'),
    url(r'^ActualizarRecurso/(?P<pk>[0-9]+)/$',
        ActualizarRecurso.as_view(), name='act-rec'),
    url(r'^EliminarRecurso/(?P<pk>[0-9]+)/$',
        EliminarRecurso.as_view(), name='elm-rec'),

    # URLS GESTION DE ASIGNACIONES
    url(r'^ListarAsignaciones/$', ListarAsignaciones.as_view(), name='lis-asi'),
    url(r'^ListarPersonaRecursos/$',
        ListarPersonaRecursos.as_view(), name='lis-per-rec'),
    url(r'^CrearAsignacion/$', CrearAsignacion.as_view(), name='cre-asi'),
    url(r'^DetalleAsignacion/(?P<pk>[0-9]+)/$',
        DetalleAsignacion.as_view(), name='det-asi'),

    url(r'^TrasladarRecursos/(?P<pk>[0-9]+)/$',
        TrasladarRecursos.as_view(), name='tra-rec'),

]

pruebadeltec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from pruebadeltec.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),

    url(r'^',
        include('app.bodega.urls', namespace='bodega')),
]

templates/asignaciones/CrearAsignacion.html
{% extends "includes/base.html" %} {% load crispy_forms_tags %} {% load static %} {% block files_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{% endblock %} {% block content %}
<br>
<div class="panel col-sm-offset-2 col-sm-8 w3-card-4 w3-border-green">
    <br>

    <form method="post">
        <center>
            <h3><b>Nueva Asignación de Recursos</b></h3></center>
        <hr> {% if msj %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{msj}}.</strong>
        </div>
        {% endif %} {% csrf_token %}

        <div class="form-group col-md-6">
            <label for="">
            {{form.recursos.label}} sin Asignar
          </label> {{form.recursos}}
            <p style="color: silver;">
                Mantenga Presionado CONTROL para Asignar mas de un Recurso
            </p>
        </div>
        <div class="form-group col-md-6">
            <label for="">
            {{form.personas.label}}
          </label><br> {{form.personas}}
            <p style="color: silver;">
                Selecciona la Persona Encargada
            </p>
        </div>
        <br>
        <div class="col-md-12">
            <center>
                <button type="submit" class="btn btn-success"> Asignar <i class="fa fa-exchange" aria-hidden="true" ></i></button>

            </center>
            <br>

        </div>

    </form>
</div>
{%endblock%} {% block files_food %} {% endblock %}

templates/asignaciones/DetalleAsignacion.html
{% extends "includes/base.html" %} {% block content %}
<center>
    <h1>Detalle de Asignacion</h1>

</center>
<hr>
<div class="container-fluid ">
  <div class="col-sm-9 col-md-offset-2 w3-card-4" style="margin-bottom: 30px; right: 1%;">

      <h4>RECURSOS ASIGNADOS a <b>{{persona}}</b>: </h4>
      <table class="table w3-table-all w3-card-4">

          <thead class="thead-inverse">
              <tr>
                  <th>Codigo</th>
                  <th>Serie</th>
                  <th>Recurso</th>
                  <th>Marca</th>

              </tr>
          </thead>
          <tbody>
            {% for asignacion in asignacion_list %}
            <tr>
                <td>
                    {{ asignacion.id_recurso.codigo }}
                </td>

                <td>
                    {{ asignacion.id_recurso.serie }}
                </td>
                <td>
                    {{ asignacion.id_recurso.nombre }}
                </td>
                <td>
                    {{ asignacion.id_recurso.marca }}
                </td>
            </tr>
            {% endfor %}
              {% for asignacion in lista_personas %}
              <tr>
                  <td>
                      {{ asignacion.id_persona.identificacion}}
                  </td>

                  <td>
                      {{ asignacion.id_persona.nombres}}
                  </td>
                  <td>
                      {{ asignacion.id_persona.apellidos}}
                  </td>
                  <td>
                      <a class="btn btn-success" href="{% url 'bodega:det-asi' asignacion.id_persona.id %}" name="btn-mod">Recursos</a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>

  </div>
  <div class="col-md-12">
      <center>

      <a href="{% url 'bodega:lis-per-rec' %}" class="btn btn-warning">Atras</a>
      </center>
      <br>
  </div>

</div>
{% endblock%}

templates/asignaciones/ListarAsignaciones.html
{% extends "includes/base.html" %} {% block content %}
<center>
  <h1>Listado de Asignaciones en el Sistema</h1>

</center>
<hr>
<div class="container-fluid ">
    <div class="table-responsive">
        <table class="table w3-table-all w3-card-4">

            <thead class="thead-inverse">
                <tr>
                    <th>Fecha de asignacion</th>
                    <th>Evento</th>
                    <th>Persona</th>
                    <th>Recurso</th>
                    <th>Codigo</th>
                    <th>Serie</th>
                </tr>
            </thead>
            <tbody>
                {% for asignacion in lista %}
                <tr>

                    <td>
                        {{ asignacion.fecha_asignacion}}
                    </td>
                    <td>{{ asignacion.evento}}</td>

                    <td>
                        {{ asignacion.id_persona.nombres}} {{ asignacion.id_persona.apellidos}}
                    </td>
                    <td>
                        {{ asignacion.id_recurso.nombre}}
                    </td>
                    <td>
                        {{ asignacion.id_recurso.codigo}}
                    </td>
                    <td>
                        {{ asignacion.id_recurso.serie}}
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock%}

templates/asignaciones/ListarPersonaRecursos.html
{% extends "includes/base.html" %} {% block content %}
<center>
  <h1>Listado de Personas con Recursos</h1>

</center>
<hr>
<div class="container-fluid ">
    <div class="table-responsive">
        <table class="table w3-table-all w3-card-4">

            <thead class="thead-inverse">
                <tr>
                    <th>Identificacion</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Recursos</th>
                    <th>Treaslado</th>


                </tr>
            </thead>
            <tbody>
                {% for persona in lista_personas %}
                <tr>
                    <td>
                        {{ persona.identificacion}}
                    </td>

                    <td>
                        {{ persona.nombres}}
                    </td>
                    <td>
                        {{ persona.apellidos}}
                    </td>
                    <td>
                        <a class="btn btn-success" href="{% url 'bodega:det-asi' persona.id %}" name="btn-mod">Recursos</a>
                    </td>
                    <td>
                      <a class="btn btn-danger" href="{% url 'bodega:tra-rec' persona.id%}" name="btn-mod">Trasladar Recursos</a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock%}

templates/asignaciones/TrasladarRecursos.html
{% extends "includes/base.html" %} {% load crispy_forms_tags %} {% load static %} {% block files_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{% endblock %} {% block content %}
<br>
<div class="panel col-sm-offset-2 col-sm-8 w3-card-4 w3-border-green">
    <br>

    <form method="post">
        <center>
            <h3><b>Traslado de Recursos de {{persona}}</b></h3></center>
        <hr> {% if msj %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{msj}}.</strong>
        </div>
        {% endif %} {% csrf_token %}

        <div class="form-group col-md-6">
            <label for="">
            {{form.recursos.label}} asignados
          </label> {{form.recursos}}
            <p style="color: silver;">
                Mantenga Presionado CONTROL para Asignar mas de un Recurso
            </p>
        </div>
        <div class="form-group col-md-6">
            <label for="">
            {{form.personas.label}}
          </label><br> {{form.personas}}
            <p style="color: silver;">
                Selecciona la Persona Encargada
            </p>
        </div>
        <br>
        <div class="col-md-12">
            <center>
                <button type="submit" class="btn btn-success"> Trasladar <i class="fa fa-exchange" aria-hidden="true" ></i></button>

            </center>
            <br>

        </div>

    </form>
</div>
{%endblock%} {% block files_food %} {% endblock %}